AllCops:
  Exclude:
    - lib/tasks/import_data_test.rake
    - db/schema.rb
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

##################### Style ##################################

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/GuardClause:
  MinBodyLength: 5

Style/Documentation:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/RedundantSelf:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

##################### Lint ##################################

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

##################### Metrics ##################################
Metrics/ModuleLength:
  Max: 300
Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*.rb"

Metrics/ClassLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 16
